<?php
/** @var $this IntegerNet_Anonymizer_Block_Anonymizer */
?>

<div class="content-header">
    <h3><?php echo $this->__('Anonymizer') ?></h3>
    <p class="form-buttons">
        <?php echo $this->getButtonHtml($this->__('Anonymize Data'), 'anonymizerForm.submit();', 'save'); ?>
    </p>
</div>

<div class="entry-edit">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="anonymizer_form">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('The following Data Types will be anonymized:') ?></h4>
            <div class="form-buttons"></div>
        </div>

        <div class="fieldset fieldset-wide" id="group_fields7">
            <ul>
                <li><?php echo $this->__('Customers'); ?></li>
                <li><?php echo $this->__('Customers Addresses'); ?></li>
                <li><?php echo $this->__('Orders'); ?></li>
                <li><?php echo $this->__('Order Addresses'); ?></li>
                <li><?php echo $this->__('Quotes'); ?></li>
                <li><?php echo $this->__('Quote Addresses'); ?></li>
                <li><?php echo $this->__('Newsletter Subscribers'); ?></li>
            </ul>
        </div>
    </form>
</div>
<script type="text/javascript">
    anonymizerForm = new varienForm('anonymizer_form', '');
</script>
